version: 1.61.0

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofumpt
    - govet
    - errcheck
    - staticcheck
    - revive
    - gosec
